export { default as Form } from '../component/form_input/Form'
export { default as Infor } from '../component/list_information/Infor.jsx'
export {default as Child} from '../component/cart-item/Child'
export { default as Header } from '../component/header/Header'
export {default as User} from '../component/InforDetail/User'